### PR TITLE
Update build.yml

### PR DESCRIPTION
**Pull request by compnerd**
The `workflow_dispatch` event is used for triggering manual jobs, `workflow_jobs` is for consumption of other jobs.

### CODE REVIEW

**Comment by haberman** [comment]
Looks like the Windows build failed: https://github.com/google/bloaty/pull/249/checks?check_run_id=3206306907

**Comment by compnerd** [comment]
Yeah, the problem is that the build configuration currently is doing some atrocious things to deal with static linking on Windows (which goes against the recommendation of upstream CMake).  There is a way to fix this, but the change requires that it propagates into protobuf, which makes it a bit more challenging.

**Comment by compnerd** [comment]
Restored the 32-bit build on Windows as #252 should repair the 32-bit builds.

**Comment by haberman** [comment]
> There is a way to fix this, but the change requires that it propagates into protobuf, which makes it a bit more challenging.

I'm on the protobuf team. If there's something in our CMake that should be improved, I can help land it.

**Comment by compnerd** [comment]
> If there's something in our CMake that should be improved, I can help land it.

Thanks for the offer ...  and since no good deed goes unpunished, expect an incoming PR for that :)

**Comment by compnerd** [comment]
ooh, and I think I figured out how to make it work without the needed change (but we should still follow up on the protobuf change just to improve protobufs).

**Comment by compnerd** [comment]
Okay, the testing isn't working yet, the builds are.  I guess that's a step forward.

**Pull request merged**
