### PR TITLE
Parsing Mach-O segments and sections directly. Parsing __LINKEDIT "sections"

### PR DESCRIPTION
**Pull request by softboysxp**

### CODE REVIEW

**Comment by softboysxp** [comment]
CLA signed.

**Comment by steipete** [comment]
I tried this branch and it worked great to expand the `__LINKEDIT` section - Thank you!

**Comment by jmkk** [comment]
It's an improvement, thank you. 
However, I tried it on iOS Mach-O files and it seems to be breaking sections file size data for a two-arch binary:

Before:
```
     VM SIZE                               FILE SIZE
 --------------                         --------------
  27.9%   642Ki [None]                   2.60Mi  62.6%
  60.1%  1.35Mi __TEXT,__text            1.35Mi  32.6%
   5.2%   119Ki __TEXT,__cstring          119Ki   2.8%
   3.2%  72.7Ki __DATA,__common               0   0.0%
   0.8%  18.5Ki __DATA,__nl_symbol_ptr   18.5Ki   0.4%
   0.6%  13.0Ki __TEXT,__const           13.0Ki   0.3%
   0.4%  8.55Ki __TEXT,__swift3_reflstr  8.55Ki   0.2%
   0.3%  7.36Ki __TEXT,__objc_methname   7.36Ki   0.2%
   0.3%  6.90Ki __DATA,__objc_const      6.90Ki   0.2%
   0.3%  6.68Ki __DATA,__const           6.68Ki   0.2%
   0.2%  5.30Ki __TEXT,__swift3_typeref  5.30Ki   0.1%
   0.2%  4.58Ki __TEXT,__swift3_fieldmd  4.58Ki   0.1%
   0.2%  4.34Ki __DATA,__data            4.34Ki   0.1%
   0.1%  1.95Ki __TEXT,__picsymbolstub4  1.95Ki   0.0%
   0.1%  1.50Ki __TEXT,__stub_helper     1.50Ki   0.0%
   0.1%  1.36Ki [Other]                     542   0.0%
   0.1%  1.30Ki __TEXT,__swift3_capture  1.30Ki   0.0%
   0.1%  1.27Ki __TEXT,__swift3_assocty  1.27Ki   0.0%
   0.0%  1.14Ki __DATA,__objc_data       1.14Ki   0.0%
   0.0%     672 __TEXT,__swift2_proto       672   0.0%
   0.0%     616 __DATA,__objc_selrefs         0   0.0%
 100.0%  2.25Mi TOTAL                    4.15Mi 100.0%
```

After:
```
     VM SIZE                                           FILE SIZE
 --------------                                     --------------
   0.0%       0 [Non-64bit arch in fat binary]       2.17Mi  52.3%
   1.6%  33.7Ki [None]                               1.98Mi  47.7%
  52.4%  1.10Mi __TEXT,__text                             0   0.0%
  23.7%   512Ki __LINKEDIT,Export Info                    0   0.0%
   6.7%   145Ki __DATA,__common                           0   0.0%
   5.5%   119Ki __TEXT,__cstring                          0   0.0%
   2.7%  59.3Ki __TEXT,__unwind_info                      0   0.0%
   1.6%  34.5Ki __LINKEDIT,Code Signature                 0   0.0%
   0.9%  18.6Ki [Other]                                   0   0.0%
   0.7%  15.9Ki __LINKEDIT,Function Start Addresses       0   0.0%
   0.6%  13.7Ki __TEXT,__const                            0   0.0%
   0.6%  12.7Ki __DATA,__objc_const                       0   0.0%
   0.5%  11.8Ki __DATA,__const                            0   0.0%
   0.4%  8.55Ki __TEXT,__swift3_reflstr                   0   0.0%
   0.4%  8.49Ki __DATA,__data                             0   0.0%
   0.3%  7.47Ki __LINKEDIT,Lazy Binding Info              0   0.0%
   0.3%  7.36Ki __TEXT,__objc_methname                    0   0.0%
   0.2%  5.30Ki __TEXT,__swift3_typeref                   0   0.0%
   0.2%  4.76Ki __LINKEDIT,String Table                   0   0.0%
   0.2%  4.58Ki __TEXT,__swift3_fieldmd                   0   0.0%
   0.2%  4.22Ki __LINKEDIT,Binding Info                   0   0.0%
 100.0%  2.11Mi TOTAL                                4.15Mi 100.0%
```

**Comment by haberman** [comment]
Thanks for this PR. I'm really sorry I never replied to it -- I was uncomfortable with depending on platform-specific headers that are only available on OS X. It seemed like it would complicate the build for non-OSX platforms.

I'm working right now on extracting the Mach-O headers so they can be included in Bloaty's third_party directory directly. This will allow it to work even on non-OS X platforms.

I think some of the problems you ran into have principled solutions. I think we can avoid special-casing `__PAGEZERO` by just excluding load commands that are mapped `VM_PROT_NONE`.

Since this PR has fallen somewhat out of date, and since I have some other ideas for how to handle these cases, I think I might just re-implement from scratch. But thanks for this contribution and sorry again that I never replied. That was rude of me.

**Comment by haberman** [comment]
On second thought, since I like a lot of the choices you made, let me merge yours first and then work from there.

Want to bring this up to date (resolve merge conflicts) and then I'll merge?

**Comment by haberman** [comment]
On third thought, I can do the merge. :) You've already signed the CLA and Git will remember the commits were authored by you, so I'll plan to do the merge myself and create a PR with this code merged with the current master branch.

**Pull request merged**
